[package]
name = "amnion"
authors = ["Soc Virnyl Estela <socvirnyl.estela@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
megalodon = { version = "0.1" }
iced = "0.4"
